# -*- coding: utf-8 -*-
"""upper_lower_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-ZWVKia4O8MMVcZjIg4LzKGpn_jbD7m
"""

sample_string = 'The quick Brow Fox'
lcount = 0
ucount = 0

for i in sample_string:
  if i.islower():
    lcount += 1
  elif i.isupper():
    ucount += 1
print('No. of Upper case characters :',ucount) 
print('No. of lower case characters :',lcount)